<?php

/* SETARILE PLATFORMEI */
$GLOBAL_CONFIG [ 'SPLIT_CHAR_URL' ] = '/' ;
$GLOBAL_CONFIG [ 'OS_SEPARATOR' ] = '/' ;
$GLOBAL_CONFIG [ 'ENGINE_FOLDER' ] = 'engine' ;
$GLOBAL_CONFIG [ 'TEMPLATE_FOLDER' ] = 'template' ;
$GLOBAL_CONFIG [ 'USE_HTACCESS' ] = false ;
$GLOBAL_CONFIG [ 'USE_HTTPS' ] = false ;
$GLOBAL_CONFIG [ 'WEB_NAME' ] = 'BEST Hackathon' ;
$GLOBAL_CONFIG [ 'HASH_KEY' ] = 'dasb12431' ;
$GLOBAL_CONFIG [ 'CHAT_URL' ] = 'http://antsy.xyz:8080' ;

/* SETARILE BAZEI DE DATE */
$GLOBAL_CONFIG [ 'DB_TYPE' ] = 'mysql' ;
$GLOBAL_CONFIG [ 'DB_HOST' ] = 'localhost' ;
$GLOBAL_CONFIG [ 'DB_DB' ] = 'steam' ;
$GLOBAL_CONFIG [ 'DB_USER' ] = 'root' ;
$GLOBAL_CONFIG [ 'DB_PASSWORD' ] = '' ;
$GLOBAL_CONFIG [ 'VERSION' ] = '1.0' ;
$GLOBAL_CONFIG [ 'API_KEY' ] = '1856B298BF464430A6BBDDFEC2D48705' ;
$GLOBAL_CONFIG [ 'OPEN_URL' ] = 'http://localhost' ;